### ISSUE TITLE
issue with asserting version

### ISSUE THREAD

**Issue by thecodeassassin** [mrlesmithjr/ansible-mariadb-galera-cluster#204] opened 2024-03-04 23:31 UTC
The mariadb version that is extracted using the CLI is not working properly.

mariadb -V
mariadb from 11.3.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper

fatal: [135.181.223.16]: FAILED! => {
    "assertion": "mariadb_version_checked.startswith(\"11.3.2\")",
    "changed": false,
    "evaluated_to": false,
    "msg": "The mariadb_version \"11.3.2\" doesn't match the one installed on the system: for. Use the correct mariadb_version or set mariadb_upgrade: True"
}

**Comment by eRadical** [comment] 2024-03-07 13:01
Duplicate of #193 
MariaDB 11.x does not have yet a LTS version.

If you can make a PR that take in consideration the discussions from #193 and supports both 10.x and 11.y - I'll be more than happy to review & merge.

Regards!

**Closed** 2024-05-17 22:28 UTC
Labels: wontfix
